apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- ../../base
- route.yaml
images:
- name: mysql
  newName: registry.redhat.io/rhel8/mysql-80
  newTag: 1-211
