apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.cluster-7wxfc-1.sandbox1710.opentlc.com
  path: "/todo"
  to:
    kind: Service
    name: frontend-dev
    weight: 100
  wildcardPolicy: None
