apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.jbocp1.sandbox2771.opentlc.com
  path: "/todo"
  to:
    kind: Service
    name: frontend-prod
    weight: 100
  wildcardPolicy: None
